# This should happen on the database server
# via https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml

---
- name: Create Postgres user for dryad
  postgresql_user: name={{ dryad.db.user }} role_attr_flags=CREATEDB password={{ dryad.db.password }} login_host={{ dryad.db.host }} port={{ dryad.db.port }}
  sudo: yes
  sudo_user: postgres

- name: Create Postgres database for Dryad
  postgresql_db: name={{ dryad.db_name }} login_user={{ dryad.db_user }} login_password={{ dryad.db_password }} encoding={{ postgresql.encoding }} lc_ctype='{{ postgresql.locale }}.{{ postgresql.encoding }}' lc_collate='{{ postgresql.locale }}.{{ postgresql.encoding }}'
