---
- name: Clone Dryad repo
  git: repo={{ dryad.repo }}
       dest={{ dryad.repo_path }}
  
- name: Copy settings.xml for maven profile
  template: src=settings.xml.j2 dest="/home/vagrant/.m2/settings.xml"

- name: Update tomcat server.xml
  debug: TODO

- name: Install build scripts
  template: src=build_dryad.sh.j2 dest="/home/vagrant/bin/build_dryad.sh"
  template: src=deploy_dryad.sh.j2 dest="/home/vagrant/bin/deploy_dryad.sh"