---
- name: Clone Dryad repo
  git: repo={{ dryad.repo }}
       dest={{ dryad.repo_path }}
  sudo: no

- name: Make m2 directory
  file: path=/home/vagrant/.m2 state=directory owner=vagrant mode=0755

- name: Copy settings.xml for maven profile
  template: src=settings.xml.j2 dest="/home/vagrant/.m2/settings.xml"
  sudo: no

- name: Update tomcat server.xml
  template: src=server.xml.j2 dest=/etc/tomcat6/server.xml backup=yes
  sudo: yes
  sudo_user: root

- name: Configure JAVA_HOME for tomcat6
  lineinfile: dest=/etc/default/tomcat6 regexp=^JAVA_HOME= line="JAVA_HOME=\"/usr/lib/jvm/java-6-oracle\""

- name: Configure JAVA_OPTS for tomcat6
  lineinfile: dest=/etc/default/tomcat6 regexp=^JAVA_OPTS line="JAVA_OPTS=\"-Xmx4096m -XX:+CMSClassUnloadingEnabled -XX:PermSize=512M -XX:MaxPermSize=512M\""

- name: Make bin directory
  file: path=/home/vagrant/bin state=directory owner=vagrant mode=0755

- name: install bash profile to update path
  copy: src=.bash_profile dest="/home/vagrant/.bash_profile" mode=0644
  sudo: no

- name: Install build script
  template: src=build_dryad.sh.j2 dest="/home/vagrant/bin/build_dryad.sh" mode=0755
  sudo: no

- name: Install deploy script
  template: src=deploy_dryad.sh.j2 dest="/home/vagrant/bin/deploy_dryad.sh" mode=0755
  sudo: no

- name: Copy carrot2-mini-3.1.0.jar for installation
  copy: src=carrot2-mini-3.1.0.jar dest=/tmp/

- name: Copy script to install missing poms
  copy: src=install_missing_poms.sh dest=/home/vagrant/bin/install_missing_poms.sh mode=0755
  sudo: no

- name: Install missing poms
  command: /home/vagrant/bin/install_missing_poms.sh chdir={{ dryad.repo_path }}/dspace/etc/discoverySnapshot
  sudo: no

- name: Make install directory
  file: path={{ dryad.install_dir }} state=directory owner=vagrant mode=0755
