---
- name: Install useful command-line tools
  apt: pkg={{ item }} state=installed update-cache=yes
#  async: 60
#  poll: 60
  with_items:
    - emacs24
    - ack-grep
    - python-pip

- name: Update awscli
  shell: pip install awscli
  become: no

